version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: timefit-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: timefit
      MYSQL_ROOT_PASSWORD: timefit0000

      MYSQL_USER: timefit-username
      MYSQL_PASSWORD: 0000

      TZ: Asia/Seoul
    volumes:
      - db_data:/var/lib/mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  app:
    build: .
    container_name: timefit-app
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/timefit?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: timefit-username
      SPRING_DATASOURCE_PASSWORD: 0000

      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      TZ: Asia/Seoul

volumes:
  db_data: