version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: timefit-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

      TZ: Asia/Seoul
    volumes:
      - db_data:/var/lib/mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  app:
    build: .
    container_name: timefit-app
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      JWT_SECRET: ${JWT_SECRET}
      TZ: Asia/Seoul

volumes:
  db_data: