spring.application.name=timefit

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:timefit
spring.datasource.username=sa
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

oauth.kakao.client-id=f939f9e98e824f5ce7592923a30ed35c
oauth.kakao.redirect-uri=http://localhost:8080/api/auth/kakao/callback