spring.application.name=timefit

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://13.124.232.236/timefit?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:timefit}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:timefit}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:b76132d7536189dbcacf214205491559e011db8f979eea8ea2149c78c7a96869}
jwt.access-token-validity-in-ms=3600000
jwt.refresh-token-validity-in-ms=1209600000
