spring.application.name=timefit

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.access-token-validity-in-ms=${ACCESS_TOKEN}
jwt.refresh-token-validity-in-ms=${REFRESH_TOKEN}

kakao.client-id=${KAKAO_CLIENT_ID}
